name: Build and Release HTML-Attribute-Folder
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.TAGGED_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "TAGGED_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and Release
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.get_version.outputs.TAGGED_VERSION }}

  update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create changelog
        uses: ./.github/actions/update
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: "v${{ needs.build.outputs.version }}"
          branch_name: ${{ github.ref_name }}

