name: Build and Release HTML-Attribute-Folder
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Get the version
        id: get_version
        run: echo "TAGGED_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get branch name
        uses: FranzDiebold/github-env-vars-action@v2
        id: get_branch

#      - name: Get branch name
#        id: get_branch
#        shell: bash
#        run: |
#          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
#            BRANCH=$(git show-ref | grep $(git rev-parse HEAD) | grep "refs/heads/" | head -n 1 | sed 's!.*/!!')
#            echo "BRANCH_NAME=${BRANCH}" >> $GITHUB_OUTPUT
#          else
#            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
#          fi

      - name: Debug
        shell: bash
        run: |
          echo "Version: ${{ steps.get_version.outputs.TAGGED_VERSION }}"
          echo "Branch : ${{ steps.get_branch.outputs.BRANCH_NAME }}"
          echo "CI_REPOSITORY_SLUG=${{ steps.get_branch.outputs.CI_REPOSITORY_SLUG }}"
          echo "CI_REPOSITORY_OWNER=${{ steps.get_branch.outputs.CI_REPOSITORY_OWNER }}"
          echo "CI_REPOSITORY_OWNER_SLUG=${{ steps.get_branch.outputs.CI_REPOSITORY_OWNER_SLUG }}"
          echo "CI_REPOSITORY_NAME=${{ steps.get_branch.outputs.CI_REPOSITORY_NAME }}"
          echo "CI_REPOSITORY_NAME_SLUG=${{ steps.get_branch.outputs.CI_REPOSITORY_NAME_SLUG }}"
          echo "CI_REPOSITORY=${{ steps.get_branch.outputs.CI_REPOSITORY }}"
          echo "CI_REF_SLUG=${{ steps.get_branch.outputs.CI_REF_SLUG }}"
          echo "CI_ACTION_REF_NAME=${{ steps.get_branch.outputs.CI_ACTION_REF_NAME }}"
          echo "CI_ACTION_REF_NAME_SLUG=${{ steps.get_branch.outputs.CI_ACTION_REF_NAME_SLUG }}"
          echo "CI_REF_NAME=${{ steps.get_branch.outputs.CI_REF_NAME }}"
          echo "CI_REF_NAME_SLUG=${{ steps.get_branch.outputs.CI_REF_NAME_SLUG }}"
          echo "CI_REF=${{ steps.get_branch.outputs.CI_REF }}"
          echo "CI_HEAD_REF_SLUG=${{ steps.get_branch.outputs.CI_HEAD_REF_SLUG }}"
          echo "CI_HEAD_REF=${{ steps.get_branch.outputs.CI_HEAD_REF }}"
          echo "CI_BASE_REF_SLUG=${{ steps.get_branch.outputs.CI_BASE_REF_SLUG }}"
          echo "CI_BASE_REF=${{ steps.get_branch.outputs.CI_BASE_REF }}"
          echo "CI_SHA_SHORT=${{ steps.get_branch.outputs.CI_SHA_SHORT }}"
          echo "CI_SHA=${{ steps.get_branch.outputs.CI_SHA }}"
          echo "CI_PR_SHA_SHORT=${{ steps.get_branch.outputs.CI_PR_SHA_SHORT }}"
          echo "CI_PR_SHA=${{ steps.get_branch.outputs.CI_PR_SHA }}"
          echo "CI_PR_NUMBER=${{ steps.get_branch.outputs.CI_PR_NUMBER }}"
          echo "CI_PR_ID=${{ steps.get_branch.outputs.CI_PR_ID }}"
          echo "CI_PR_TITLE=${{ steps.get_branch.outputs.CI_PR_TITLE }}"
          echo "CI_PR_DESCRIPTION=${{ steps.get_branch.outputs.CI_PR_DESCRIPTION }}"
          echo "CI_ACTOR=${{ steps.get_branch.outputs.CI_ACTOR }}"
          echo "CI_EVENT_NAME=${{ steps.get_branch.outputs.CI_EVENT_NAME }}"
          echo "CI_RUN_ID=${{ steps.get_branch.outputs.CI_RUN_ID }}"
          echo "CI_RUN_NUMBER=${{ steps.get_branch.outputs.CI_RUN_NUMBER }}"
          echo "CI_WORKFLOW=${{ steps.get_branch.outputs.CI_WORKFLOW }}"
          echo "CI_ACTION=${{ steps.get_branch.outputs.CI_ACTION }}"

#      - name: Setup Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'oracle'
#          java-version: 21
#
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
#
#      - name: Build PlugIn
#        run: ./gradlew buildPlugin
#
#      - name: Release PlugIn
#        uses: ncipollo/release-action@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          artifacts: "build/distributions/html-attribute-folder-*.zip"
#          name: "html-attribute-folder-${{ steps.get_version.outputs.TAGGED_VERSION }}.zip"
#
#      - name: Generate changelog
#        uses: BobAnkh/auto-generate-changelog@v1.2.5
#        with:
#          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          COMMIT_MESSAGE: "docs(changelog): 📚 Update release notes for ${{ steps.get_version.outputs.TAGGED_VERSION }}"
#          TYPE: "feat:Feature,fix:Fixes,docs:Documentation"
#          BRANCH: ${{ steps.get_branch.outputs.BRANCH_NAME }}
#
#      - name: Update version tag
#        shell: bash
#        run: |
#          echo "Version: ${{ steps.get_version.outputs.TAGGED_VERSION }}"
#
#          CURRENT_GIT_TAG="v${{ steps.get_version.outputs.TAGGED_VERSION }}"
#          EXISTING_TAG=$(git tag -l "${CURRENT_GIT_TAG}")
#          if [ -n "$EXISTING_TAG" ]; then
#            echo "Version tag '$CURRENT_GIT_TAG' already exists. Deleting and updating the tag."
#            git tag -d "${CURRENT_GIT_TAG}"
#          fi
#          git tag "${CURRENT_GIT_TAG}"
#          git push origin "${CURRENT_GIT_TAG}" --force
#          echo "Updated version tag: ${CURRENT_GIT_TAG}"

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    outputs:
#      version: ${{ steps.get_version.outputs.TAGGED_VERSION }}
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Get version
#        id: get_version
#        run: echo "TAGGED_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
#
#      - name: Build and Release
#        uses: ./.github/actions/build
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          version: ${{ steps.get_version.outputs.TAGGED_VERSION }}
#
#  update:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Create changelog
#        uses: ./.github/actions/update
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          version: "v${{ needs.build.outputs.version }}"
#          branch_name: ${{ github.ref_name }}
#
