name: Generate HTML-Attribute-Folder-Changelog
on:
  workflow_run:
    workflows:
      - Build HTML-Attribute-Folder # Name des vorherigen Workflows
    types:
      - completed
jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get Tag from Previous Workflow
        id: fetch_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WORKFLOW_RUN_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
          echo "Fetching event data from: $WORKFLOW_RUN_URL"
          
          # API-Call to get metadata of the workflow run
          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $WORKFLOW_RUN_URL)
          echo "API Response: $RESPONSE"

          # Parse the Tag from the Response
          TAG=$(echo "$RESPONSE" | jq -r '.head_commit.message')

          # Verify if Tag was Found
          if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
            echo "Error: Could not find tag!"
            exit 1
          fi

          TAG=${TAG#refs/tags/}
          echo "Detected Tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
